export const services = [
  {
    image: '/images/services/whatsapp.png',
    title: 'Whatsapp',
    href: 'whatsapp',
    desc: 'WhatsApp is a messaging and calling app that allows users to communicate with each other in real time. It uses the internet to send text messages, images, audio and video messages, as well as make voice and video calls. With its user-friendly interface, WhatsApp is a convenient and reliable way to stay connected with friends and family.',
  },
  {
    image: '/images/services/telegram.png',
    title: 'Telegram',
    href: 'telegram',
    desc: 'Telegram is a cloud-based instant messaging and VoIP service which allows users to send and receive messages, photos, videos, and other files. Telegram allows users to create group chats and channels for broadcasting messages to large audiences. It also provides end-to-end encryption and optional secret chats, which are encrypted messages that can be set to self-destruct after a certain time.',
  },
  {
    image: '/images/services/facebook.png',
    title: 'Facebook',
    href: 'facebook',
    desc: "Facebook is a social media platform that allows to connect with family, friends, and colleagues from all over the world. Users can post statuses, photos, videos, and events, as well as like and comment on others' posts. On Facebook, users can join groups and pages for like-minded people, create and manage events, and play games. Facebook also provides users with the opportunity to advertise their business or products. On October 28, 2021, Facebook formally changed its name to Meta, becoming part of a metaverse where users will be able to communicate in virtual reality.",
  },
  {
    image: '/images/services/google.png',
    title: 'Google/Youtube/Gmail',
    href: 'google',
    desc: 'Google is a search engine that provides easy access to information from around the world. Youtube is a video streaming service that allows to upload, watch, and share videos. Gmail is a free email service from Google that provides an easy to use, secure and reliable way to send and receive emails.',
  },
  {
    image: '/images/services/pof_com.png',
    title: 'Plenty Of Fish',
    href: 'pof_com',
    desc: 'Plenty of Fish is an online dating service that allows users to create a profile, view and connect with potential matches, and message them. It has a variety of features, including its Chemistry Predictor, which helps users find compatible partners.',
  },
  {
    image: '/images/services/paypal.png',
    title: 'Paypal',
    href: 'paypal',
    desc: 'PayPal is an online payment service that allows you to securely send and receive money from individuals and businesses. It is a convenient and secure way to make payments and purchases over the internet. It is free to sign up and users can link their bank account or credit card to quickly and easily send money. PayPal also provides buyers and sellers with dispute resolution and fraud protection.',
  },
  {
    image: '/images/services/twitter.png',
    title: 'Twitter',
    href: 'twitter',
    desc: "Twitter is a popular social media platform that allows users to share short messages, called tweets, with other users. Twitter users can follow each other and respond to each other's tweets, creating an online conversation. Twitter also allows users to search for topics and news, and to join conversations related to those topics. Additionally, Twitter users have the ability to share images, videos, and links.",
  },
  {
    image: '/images/services/ebay.png',
    title: 'Ebay',
    href: 'ebay',
    desc: "Ebay is an online marketplace where people can buy and sell a variety of goods and services. Ebay allows sellers to list items for auction, and buyers to purchase items at fixed prices. Ebay's easy-to-use platform makes it one of the most popular online marketplaces in the world.",
  },
  {
    image: '/images/services/amazon.png',
    title: 'Amazon',
    href: 'amazon',
    desc: 'Amazon Service is a cloud-computing platform that provides a wide range of services to businesses and individuals. It includes services for storage, computing power, database management, analytics, and more. Amazon Service is designed to be highly scalable and reliable, making it a great choice for businesses looking to expand their operations or reduce costs. It also provides a range of security features to keep customer data safe.',
  },
  {
    image: '/images/services/uber.png',
    title: 'Uber',
    href: 'uber',
    desc: 'Uber is a ride-sharing service that operates in many cities worldwide. It connects passengers to drivers through the Uber App, allowing passengers to request a ride from a driver nearby. Uber has a variety of vehicle options to choose from, ranging from economy cars to luxury SUVs. Additionally, Uber offers services such as Uber Eats and Uber Pool, which allow passengers to order food and share a ride with other passengers respectively.',
  },
  {
    image: '/images/services/bolt.png',
    title: 'Bolt',
    href: 'bolt',
    desc: 'Bolt is an on-demand transportation platform that connects drivers and passengers through a smartphone app. It offers users a convenient, affordable, and safe way to get rides to their destination. Drivers use the app to pick up passengers and receive payment for their services. Passengers can request rides, track drivers, and pay for services all in one place.',
  },
  {
    image: '/images/services/netflix.png',
    title: 'Netflix',
    href: 'netflix',
    desc: 'Netflix is an online streaming service that allows users to watch a variety of TV shows, movies, and documentaries. It offers a range of subscription plans watch content on multiple devices. Netflix offers an extensive library of original movies and series, as well as exclusive content from other sources not available anywhere else.',
  },
  {
    image: '/images/services/tiktok.png',
    title: 'Tiktok/Douyin',
    href: 'tiktok',
    desc: 'TikTok / Douyin is a popular short video sharing app and social media platform. It allows users to create short videos and lip-sync to music, as well as share their videos with friends and family. It also has lots of fun filters, effects, and other editing tools to make videos even more creative. The app also has a large community of users who can like, comment, and share videos with each other.',
  },
  {
    image: '/images/services/discord.png',
    title: 'Discord',
    href: 'discord',
    desc: 'Discord is an online chat platform that allows users to discuss topics, play games, and connect with others. It has a variety of features, including voice and video calls, text chat, file sharing, and more. Discord is popular among gamers, streamers, and other communities and is a great way to stay connected with friends and family.',
  },
  {
    image: '/images/services/tinder.png',
    title: 'Tinder',
    href: 'tinder',
    desc: 'Tinder is a popular dating app that allows users to swipe right or left on potential matches. It is easy to use and allows users to quickly find potential matches in their area. Tinder also utilizes its own algorithm to suggest compatible matches based on users preferences. The app is free to use and provides users with a fun and convenient way to meet new people.',
  },
  {
    image: '/images/services/instagram.png',
    title: 'Instagram',
    href: 'instagram',
    desc: 'Instagram is a social media platform that allows users to share photos, videos and stories with their followers. It also offers a range of creative tools such as filters, interactive stickers and stories to enhance content. Brands can promote their products and services through sponsored posts and ads on Instagram.',
  },
  {
    image: '/images/services/deliveroo.png',
    title: 'Deliveroo',
    href: 'deliveroo',
    desc: 'Deliveroo is an online food delivery service that allows customers to order food from their favorite restaurants, delivered to their doorstep. It is easy to use, with customers able to customize their orders, track progress and even leave special instructions. Deliveroo also offers a range of payment methods and a loyalty program.',
  },
  {
    image: '/images/services/battle_net.png',
    title: 'Battle.Net Blizzard',
    href: 'battle_net',
    desc: "Battle.Net is Blizzard's online gaming service that allows to play games, connect with friends, and manage Blizzard accounts. The service offers a range of features such as automatic game patching, in-game chat, in-game friends list, and more. It also provides online store to purchase games, expansions, and other gaming content.",
  },
  {
    image: '/images/services/getir.png',
    title: 'Getir',
    href: 'getir',
    desc: 'Getir is an on-demand delivery service that allows customers to order groceries, household items and more with just a few clicks. Customers can select from a wide range of products and have them delivered to their doorstep in a matter of minutes. Getir also offers a subscription service to save the preferences and get the orders delivered even faster.',
  },
  {
    image: '/images/services/didi.png',
    title: 'Didi',
    href: 'didi',
    desc: 'Didi is an on-demand transportation platform that serves over 550 million users in more than 400 cities in China. It offers a wide range of services, including taxi-hailing, carpooling, bus and shuttle services, designated drivers, and bike rentals. It also provides users with numerous convenience features, such as real-time traffic updates, route optimization, and digital payments.',
  },
  {
    image: '/images/services/wolt.png',
    title: 'Wolt',
    href: 'wolt',
    desc: 'Wolt is a food delivery service that connects customers with restaurants. Customers can order meals from a wide range of restaurants and have them delivered to their door quickly and conveniently. Wolt also offers additional services such as grocery delivery, alcohol delivery, and restaurant reservations. Wolt has delivery partners in over 120 cities around the world.',
  },
  {
    image: '/images/services/no_icon.png',
    title: 'Openai',
    href: 'openai',
    desc: "Openai is an artificial intelligence research laboratory based in San Francisco, California. It was founded in 2015 by Elon Musk, Sam Altman, Greg Brockman and others. Openai's mission is to develop technologies that will allow artificial general intelligence (AGI) to benefit humanity. Openai works with a variety of partners and sponsors to research, develop and deploy AGI technologies. Openai also provides services and products to help developers and companies build and deploy AI-powered applications.",
  },
  {
    image: '/images/services/careem.png',
    title: 'Careem',
    href: 'careem',
    desc: 'Careem is a ride-hailing service that operates in the Middle East, North Africa and South Asia. It provides a safe, reliable and convenient way to get around town. It has a wide range of vehicles, from luxury cars to economy cars, to suit different needs. Customers can book a ride from the Careem app and track the progress of their ride in real-time. The fare is calculated upfront and is paid securely through the app.',
  },
  {
    image: '/images/services/nike.png',
    title: 'Nike',
    href: 'nike',
    desc: 'Nike is a global leader in athletic footwear, apparel, equipment and accessories. Nike offers a range of services to suit every athlete, including product customization, personalized shopping experiences, and specialized customer support. Nike also offers a variety of delivery and return options for customers.',
  },
];

export const countries = [
  {
    image: '/images/countries/gb.png',
    title: 'United Kingdom',
    href: 'united-kingdom',
    desc: "The United Kingdom of Great Britain (UK) is a sovereign country located off the north-western coast of the European mainland. It is an island country comprising of England, Wales, Scotland and Northern Ireland. It is the world's sixth-largest economy, with a GDP of $2.8 trillion in 2019 and the fourth-most populous country in Europe. The UK is a developed country with a high-income economy and is a member of the European Union, the G7, and the G20.",
  },
  {
    image: '/images/countries/us.png',
    title: 'United States',
    href: 'united-states',
    desc: "The United States of America is a federal republic composed of 50 states, a federal district, five major self-governing territories, and various possessions. At 3.8 million square miles and with over 325 million people, the United States is the world's third- or fourth-largest country by total area and the third-most populous. The capital is Washington, D.C., and the largest city by population is New York City.",
  },
  {
    image: '/images/countries/in.png',
    title: 'India',
    href: 'india',
    desc: "India is a country in South Asia with a population of over 1.3 billion people. It is the world's second most populous country. India has one of the world's fastest growing economies and is the world's third largest economy in terms of purchasing power parity. India is a culturally diverse nation with over 22 official languages and multiple religions.",
  },
  {
    image: '/images/countries/br.png',
    title: 'Brazil',
    href: 'brazil',
    desc: "Brazil is the largest country in both South America and Latin America. Its capital is Brasília, and its most populated city is São Paulo. It is the world's fifth-largest country, both by geographical area and by population, with over 209 million people. Brazil is home to a diverse array of wildlife and is known for its extensive natural resources, including the Amazon River and the Amazon Rainforest. It is also known for its cultural heritage, with Portuguese being its official language.",
  },
  {
    image: '/images/countries/my.png',
    title: 'Malaysia',
    href: 'malaysia',
    desc: 'Malaysia is a Southeast Asian country located on the Malay Peninsula and the island of Borneo. It is one of the most prosperous and stable countries in the region, with its economy being among the most competitive in the world. Malaysia is known for its diverse culture, with its population composed of Malays, Chinese, Indians, and numerous other ethnic groups. The country is also known for its natural beauty and its many national parks.',
  },
  {
    image: '/images/countries/ru.png',
    title: 'Russia',
    href: 'russia',
    desc: "Russia is a large country in Eastern Europe and northern Asia. It is the largest country in the world, covering more than one-eighth of the Earth's inhabited land area. Its landscape is diverse, ranging from tundra and forests to subtropical beaches. Russia is known for its rich cultural heritage, including its art, music, and literature. It is also home to many renowned universities and museums.",
  },
  {
    image: '/images/countries/it.png',
    title: 'Italy',
    href: 'italy',
    desc: 'Italy is a country located in Southern Europe. It is a founding member of the European Union and home to the third-largest economy in the eurozone. It is the 8th-most visited country in the world, with over 60 million tourists annually. Italy is known for its rich history, culture and art, and its famous cities such as Rome, Milan and Venice. Italy is also renowned for its cuisine, fashion, design and automobile industry.',
  },
  {
    image: '/images/countries/id.png',
    title: 'Indonesia',
    href: 'indonesia',
    desc: "Indonesia is a sovereign state located in Southeast Asia, between the Indian and Pacific Oceans. With over 265 million people, it is the world's fourth most populous country and the most populous Muslim-majority country. The Indonesian archipelago is composed of more than 17,000 islands, and its capital and largest city is Jakarta.",
  },
  {
    image: '/images/countries/cn.png',
    title: 'China',
    href: 'china',
    desc: "China is a country located in East Asia that has a population of over 1.4 billion people. It is the world's most populous country and the second largest by land area. China has a long history and is one of the world's oldest civilizations. Its culture is diverse and complex, with many unique customs and traditions. China is a rapidly developing country with a booming economy and a rapidly growing middle class. It is also the world's largest exporter of goods and the world's second largest economy.",
  },
  {
    image: '/images/countries/sa.png',
    title: 'Saudi Arabia',
    href: 'saudi-arabia',
    desc: 'Saudi Arabia is a desert country located in the Middle East. The country is known for its vast oil reserves and has been an important player in the global energy market for decades. It is home to the two holiest sites in Islam, the cities of Mecca and Medina. The country is governed by a monarchy and is known for its conservative Islamic laws and customs.',
  },
  {
    image: '/images/countries/mx.png',
    title: 'Mexico',
    href: 'mexico',
    desc: 'Mexico is a country in North America bordered by the United States to the north and the Pacific Ocean to the south. Mexico has a diverse geography that includes deserts, jungles, and high mountains. The population of Mexico is around 125 million people and is made up of a mix of cultures including Spanish and Afro-Mexican. The capital of Mexico is Mexico City, and the currency is the Mexican peso. The official language is Spanish, but many people also speak English and indigenous languages.',
  },
  {
    image: '/images/countries/tr.png',
    title: 'Turkey',
    href: 'turkey',
    desc: 'Turkey is a country located in both Europe and Asia, with a population of over 80 million people. It has a rich history, stretching back to the Ottoman Empire. It is also a popular tourist destination, with its many ancient ruins, beaches, and natural wonders. Turkey is an important regional power and a major player in international affairs.',
  },
  {
    image: '/images/countries/de.png',
    title: 'Germany',
    href: 'germany',
    desc: 'Germany is a country located in Central Europe. It has a population of over 82 million people and is the largest economy in Europe. It is a federal republic consisting of 16 states and is bordered by nine other countries. Germany is known for its rich culture, automotive industry, and its world-famous Oktoberfest. It is also home to some of the most beautiful cities in Europe, such as Berlin, Munich, and Hamburg.',
  },
  {
    image: '/images/countries/fr.png',
    title: 'France',
    href: 'france',
    desc: 'France is a country located in Western Europe. It is the largest country in the European Union. France is known for its rich culture and gastronomy. It has a wide range of landscapes, from the Mediterranean beaches to the mountain peaks in the Alps and Pyrenees. In addition, it is also famous for its fashion, art and literature.',
  },
  {
    image: '/images/countries/ca.png',
    title: 'Canada',
    href: 'canada',
    desc: 'Canada is a country located in North America with many natural wonders and a wide variety of cultures. Canada is a bilingual nation, with English and French often spoken in both official languages. The capital city of Canada is Ottawa, located in the province of Ontario. Canada is known for its vast natural landscapes, from the Rocky Mountains in the west to the Arctic tundra in the north. It is also home to a rich culture, with many unique festivals and events throughout the year.',
  },
  {
    image: '/images/countries/vn.png',
    title: 'Viet Nam',
    href: 'viet-nam',
    desc: 'Vietnam is a country located in Southeast Asia, bordered by China, Laos, and Cambodia. It is most known for its natural beauty, with a long coastline, beautiful beaches, and lush jungles. Vietnam is also home to vibrant cities, rich culture and history, and delicious cuisine. The country is rapidly developing and growing in popularity as a tourist destination.',
  },
  {
    image: '/images/countries/gh.png',
    title: 'Ghana',
    href: 'ghana',
    desc: 'Ghana is a country located in West Africa. It is bordered by the Ivory Coast, Burkina Faso, Togo, and the Gulf of Guinea. The capital of Ghana is Accra, and its official language is English. Ghana is known for its diverse wildlife and national parks, as well as its rich cultural heritage. It is also home to numerous festivals and celebrations, including the Akwasidae Festival and the Panafest Festival.',
  },
  {
    image: '/images/countries/ae.png',
    title: 'United Arab Emirates',
    href: 'united-arab-emirates',
    desc: 'The United Arab Emirates is a country located in the southeast of the Arabian Peninsula. It has a population of 9.4 million people, whose primary language is Arabic. The country is made up of seven emirates and is the second largest economy in the Middle East. The UAE has become a major hub for business and trade, due to its strategic location and excellent infrastructure. It is also known for its rich cultural heritage and its impressive man-made attractions, such as the Burj Khalifa and the Palm Islands.',
  },
  {
    image: '/images/countries/es.png',
    title: 'Spain',
    href: 'spain',
    desc: 'Spain is a country located in southwestern Europe. It is the second-largest country on the continent and has a population of around 46 million people. It is known for its vibrant culture, delicious cuisine, stunning landscapes, and interesting history. Its capital city, Madrid, is known for its art, gastronomy, and nightlife. Spain is also known for its beautiful beaches and its many festivals, such as the famous Running of the Bulls in Pamplona.',
  },
  {
    image: '/images/countries/nl.png',
    title: 'Netherlands',
    href: 'netherlands',
    desc: 'The Netherlands is a country located in western Europe. It is bordered by Germany, Belgium, and the North Sea. The capital city is Amsterdam, which is known for its beautiful canals, art galleries, and nightlife. It is a highly developed country with a strong economy and advanced infrastructure. The official language is Dutch, but English is also widely spoken.',
  },
  {
    image: '/images/countries/at.png',
    title: 'Austria',
    href: 'austria',
    desc: 'Austria is a Central European country. Austria is a federal republic with a parliamentary democracy, with its capital in Vienna. It is home to the world famous Vienna Philharmonic Orchestra and the Danube River. Austria is known for its majestic alpine landscapes, Baroque architecture and cultural heritage.',
  },
  {
    image: '/images/countries/pe.png',
    title: 'Peru',
    href: 'peru',
    desc: 'Peru is a country located in the western part of South America. It has a population of over 30 million people and the official language is Spanish. The capital city is Lima and it is home to a number of historical attractions, cultural sites and natural wonders. It is home to the famous Machu Picchu, a UNESCO World Heritage Site.',
  },
  {
    image: '/images/countries/th.png',
    title: 'Thailand',
    href: 'thailand',
    desc: 'Thailand is a beautiful and vibrant country located in Southeast Asia. It is bordered by Myanmar, Laos, Cambodia and Malaysia. With white sandy beaches, crystal clear waters, lush jungles, and amazing cuisine, Thailand is a popular tourist destination. The culture is diverse and exciting, and the people are known for their hospitality. Thailand has a rich history, with ancient Buddhist temples and ruins, and modern cities with a bustling nightlife.',
  },
  {
    image: '/images/countries/ie.png',
    title: 'Ireland',
    href: 'ireland',
    desc: 'Ireland is a small island country located off the western coast of Britain. It is known for its rolling green hills, ancient Celtic culture, and friendly people. It is also home to many historic sites and some of the most stunning coastline views in the world. The Irish have a long-standing tradition of music, literature, and storytelling which is still celebrated today. The country is also a popular tourist destination known for its pubs and traditional hospitality.',
  },
];
